//! Regenerates the `.tok-*` syntax-highlighting block at the tail of
//! `static/css/main.css`. Run with `cargo run --example gen_css [OUT]`.
//!
//! The block is syntect's `css_for_theme_with_class_style(GitHub, "tok-")`
//! output — a pure function of the theme, not of the languages loaded at
//! boot. Keeping the generator committed makes the committed CSS reproducible
//! when the theme or syntect version changes.
//!
//! Treeshake: selectors whose scope names a language this blog does not
//! render (css/js/json/php/ruby/scss/diff/git) are dropped. Generic scope
//! rules (comment, string, keyword, ...) are kept and serve rust/c/vhdl;
//! python and markdown rules are kept too. `html` is an atom coupled only to
//! markdown (no standalone html source rules), so it is kept.

use std::io::Write;
use std::path::PathBuf;

use syntect::highlighting::ThemeSet;
use syntect::html::{ClassStyle, css_for_theme_with_class_style};

/// Scope atoms naming languages NOT rendered by this blog. A selector
/// containing any of these is dropped.
const EXCLUDED_LANGS: &[&str] = &[
    "css",
    "js",
    "json",
    "php",
    "ruby",
    "scss",
    "diff",
    "git",
    "git_gutter",
];

struct Rule {
    selector: String,
    body: String,
}

fn keep_selector(selector: &str) -> bool {
    !selector
        .split(['.', ' ', ','])
        .filter(|t| !t.is_empty())
        .map(|t| t.strip_prefix("tok-").unwrap_or(t))
        .any(|atom| EXCLUDED_LANGS.contains(&atom))
}

/// Split syntect's single-`{`-per-line rule format, preserving selector and
/// body text verbatim so regeneration is byte-identical (minus treeshaking).
fn split_rules(generated: &str) -> Vec<Rule> {
    let mut rules = Vec::new();
    let mut cur: Option<String> = None;
    let mut body = String::new();
    for line in generated.lines() {
        if cur.is_some() {
            if line == "}" {
                rules.push(Rule {
                    selector: cur.take().unwrap(),
                    body: std::mem::take(&mut body),
                });
            } else {
                body.push_str(line);
                body.push('\n');
            }
        } else if line.trim_end().ends_with('{') {
            cur = Some(line.trim_end_matches('{').trim_end().to_string());
        }
    }
    rules
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let default = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("static/css/main.css");
    let path = std::env::args()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or(default);

    let original = std::fs::read_to_string(&path)?;
    let lines: Vec<&str> = original.lines().collect();
    let marker = lines
        .iter()
        .position(|l| *l == " * theme \"GitHub\" generated by syntect")
        .ok_or("generated-block banner not found")?;
    let mut start = marker;
    while start > 0 && !lines[start].starts_with("/*") {
        start -= 1;
    }
    let prefix = lines[..start].join("\n");

    let ts = ThemeSet::load_defaults();
    // The theme's display name is "GitHub" though its dump is keyed
    // "InspiredGitHub"; match on display name to survive key renames.
    let theme = ts
        .themes
        .iter()
        .find(|(_, t)| t.name.as_deref() == Some("GitHub"))
        .map(|(_, t)| t)
        .ok_or("GitHub theme not found in default ThemeSet")?;
    let generated =
        css_for_theme_with_class_style(theme, ClassStyle::SpacedPrefixed { prefix: "tok-" })?;

    let rules = split_rules(&generated);
    let kept: Vec<&Rule> = rules
        .iter()
        .filter(|r| keep_selector(&r.selector))
        .collect();

    let mut block = String::new();
    for r in &kept {
        block.push_str(&r.selector);
        block.push_str(" {\n");
        block.push_str(&r.body);
        block.push_str("}\n");
    }

    let banner = "/*\n * theme \"GitHub\" generated by syntect\n * (treeshaken to rust/markdown/python/c/vhdl)\n */\n\n";
    let out = format!("{prefix}\n{banner}{block}");

    let mut f = std::fs::File::create(&path)?;
    f.write_all(out.as_bytes())?;
    eprintln!(
        "wrote {}: kept {}/{} rules (dropped {})",
        path.display(),
        kept.len(),
        rules.len(),
        rules.len() - kept.len()
    );
    Ok(())
}
